name: ArrowRide
version: 1.0.8
main: com.arrowride.ArrowRide
author: Benjamin Bravo
api-version: 1.21.1

commands:
  arrowride:
    permission: "ArrowRide.admin"
    description: Toggles various forms of arrow riding
    aliases:
      - ar
    usage: "Usage: /<command> [enable|disable] [mobs|explosions]"

permissions:
  Arrowride.admin:
    description: use arrowride commands
    default: op
  Arrowride.use:
    description: allow usage
    default: true